<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Features\Flights\Domain\Airport.Features.Flights.Domain.csproj" />
    <ProjectReference Include="..\..\src\Features\Flights\Application\Airport.Features.Flights.Application.csproj" />
    <ProjectReference Include="..\..\src\Features\Flights\Infrastructure\Airport.Features.Flights.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Features\Flights\Presentation\Api\Airport.Features.Flights.Presentation.Api.csproj" />
    <ProjectReference Include="..\..\src\Features\Flights\Presentation\Web\Airport.Features.Flights.Presentation.Web.csproj" />
    <ProjectReference Include="..\..\src\Features\Auth\Domain\Airport.Features.Auth.Domain.csproj" />
    <ProjectReference Include="..\..\src\Features\Auth\Application\Airport.Features.Auth.Application.csproj" />
    <ProjectReference Include="..\..\src\Features\Auth\Infrastructure\Airport.Features.Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Features\Auth\Presentation\Api\Airport.Features.Auth.Presentation.Api.csproj" />
    <ProjectReference Include="..\..\src\Features\Auth\Presentation\Web\Airport.Features.Auth.Presentation.Web.csproj" />
    <ProjectReference Include="..\..\src\Features\Bookings\Domain\Airport.Features.Bookings.Domain.csproj" />
    <ProjectReference Include="..\..\src\Features\Bookings\Application\Airport.Features.Bookings.Application.csproj" />
    <ProjectReference Include="..\..\src\Features\Bookings\Infrastructure\Airport.Features.Bookings.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Features\Bookings\Presentation\Web\Airport.Features.Bookings.Presentation.Web.csproj" />
  </ItemGroup>
</Project>
