<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d76b60a0-1980-4de5-b77a-6775898db647</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Airport.Core\Airport.Core.csproj" />
    <ProjectReference Include="..\Airport.Infrastructure\Airport.Infrastructure.csproj" />
  </ItemGroup>

</Project>
