<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Airport.Features.Bookings.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Airport.SharedKernel\Airport.SharedKernel.csproj" />
  </ItemGroup>
</Project>
