<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d76b60a0-1980-4de5-b77a-6775898db647</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Airport.Caching\Airport.Caching.csproj" />
    <ProjectReference Include="..\..\Features\Administration\Presentation\Api\Airport.Features.Administration.Presentation.Api.csproj" />
    <ProjectReference Include="..\..\Features\Auth\Presentation\Api\Airport.Features.Auth.Presentation.Api.csproj" />
    <ProjectReference Include="..\..\Features\Flights\Presentation\Api\Airport.Features.Flights.Presentation.Api.csproj" />
    <ProjectReference Include="..\..\Features\Payments\Presentation\Api\Airport.Features.Payments.Presentation.Api.csproj" />
  </ItemGroup>

</Project>
