<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\Application\Airport.Features.Administration.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Airport.Features.Administration.Infrastructure.csproj" />
  </ItemGroup>
</Project>
